# Generated by Django 4.0.3 on 2022-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_signup_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup_table',
            name='picture',
            field=models.FileField(null='True', upload_to='profile_picture'),
            preserve_default='True',
        ),
    ]
