# Generated by Django 4.0.3 on 2022-04-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_signup_table_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('rating', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
