# Generated by Django 4.0.3 on 2022-04-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0004_add_feedback_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_feedback_table',
            name='serial',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
