# Generated by Django 4.0.3 on 2022-04-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_add_feedback_table_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_feedback_table',
            name='serial',
        ),
    ]
