# Generated by Django 4.0.3 on 2022-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_remove_add_feedback_table_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_feedback_table',
            name='logger_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
