# Generated by Django 4.0.3 on 2022-05-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_add_feedback_table_logger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_cart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
