# Generated by Django 4.0.3 on 2022-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0008_add_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_drive_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive', models.CharField(max_length=100)),
                ('transaction', models.CharField(max_length=50)),
                ('tid', models.CharField(max_length=50)),
                ('doc', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
