# Generated by Django 4.0.3 on 2022-05-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_add_drive_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_drive_table',
            name='logger_id',
            field=models.IntegerField(null='True'),
        ),
    ]
