# Generated by Django 4.0.3 on 2022-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_alter_add_drive_table_logger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_drive_table',
            name='logger_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
