# Generated by Django 4.0.3 on 2022-05-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_alter_add_drive_table_logger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=70)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
