# Generated by Django 4.0.3 on 2022-05-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_add_report_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('date', models.CharField(max_length=20)),
                ('income', models.IntegerField()),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
