# Generated by Django 4.0.3 on 2022-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_add_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pcode', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=50)),
                ('pdate', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('tid', models.CharField(max_length=10)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
