# Generated by Django 4.0.3 on 2022-05-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_add_booking_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_land_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltype', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('benefits', models.CharField(max_length=150)),
                ('drawbacks', models.CharField(max_length=150)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
