# Generated by Django 4.0.3 on 2022-06-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0017_add_duration_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_equipment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('time', models.CharField(max_length=15)),
                ('total', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
