# Generated by Django 4.0.3 on 2022-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0018_add_equipment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_farmer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('adhar', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=50)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
