# Generated by Django 4.0.3 on 2022-06-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0019_add_farmer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_farmer_table',
            name='adhar',
            field=models.CharField(max_length=12),
        ),
    ]
