# Generated by Django 4.0.3 on 2022-06-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_add_vendor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_fertilizer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=20)),
                ('logger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_pesticide_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=20)),
                ('logger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('condition', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('logger_id', models.IntegerField()),
            ],
        ),
    ]
